[theme]
primaryColor = "#FF69B4"
backgroundColor = "#FFF0F5"
secondaryBackgroundColor = "#FFE4E1"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[server]
headless = true
port = 8501

